[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/book/salon/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/discover"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_ANON_KEY = "" 